sonar.projectKey=spring-frontend
sonar.projectName=Spring frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target
sonar.sourceEncoding=UTF-8
sonar.host.url=http://sonarqube:9000
sonar.login=admin
sonar.password=1583587946asD_
